# SQL Database Information
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task-management?useSSL=false
    username: admin
    password: admin
server: 8080

# Log SQL
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE